# Generated by Django 4.2.7 on 2025-07-02 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_django", "0004_alter_code_timestamp_alter_partial_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="code",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, default=datetime.datetime(2025, 7, 2, 15, 8, 32, 282235)
            ),
        ),
        migrations.AlterField(
            model_name="partial",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, default=datetime.datetime(2025, 7, 2, 15, 8, 32, 282694)
            ),
        ),
        migrations.AlterField(
            model_name="usersocialauth",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 7, 2, 15, 8, 32, 280235)
            ),
        ),
    ]
