# Generated by Django 4.2.7 on 2025-06-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lxpapp', '0003_poll_option'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Option',
            new_name='PollOption',
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_type',
            field=models.CharField(choices=[('dynamic', 'Dynamic'), ('yesno', 'Yes/No')], default='dynamic', max_length=10),
        ),
    ]
