# Generated by Django 4.2.7 on 2025-07-02 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lxpapp", "0004_rename_option_polloption_alter_poll_poll_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="polloption",
            name="votes",
        ),
        migrations.AddField(
            model_name="poll",
            name="eligible_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select groups that are eligible to vote on this poll. Leave empty to allow all logged-in users.",
                to="auth.group",
            ),
        ),
        migrations.CreateModel(
            name="PollVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="lxpapp.polloption",
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="lxpapp.poll",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "poll")},
            },
        ),
    ]
