name: Deploy Flask App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy via native SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ 'ubuntu' }}@${{ secrets.SSH_IP }} << 'EOF'
            cd ~/polling-app
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart polling
          EOF
